### ISSUE TITLE
the main `React.useEffect is missing a dependency on the props

### ISSUE THREAD

**Issue by mmomtchev** [eunchurn/react-windrose-chart#142]
Which means that if the props (the data) changes, you must resize the window for the component to be refreshed

**Comment by eunchurn** [comment]
Have you replace component with [@eunchurn/react-windrose](https://github.com/eunchurn/components/packages/1399456)? This component has responsive size from parent https://github.com/eunchurn/components/blob/main/packages/react-windrose/src/WindRose/WindRoseChart.component.tsx

**Comment by eunchurn** [comment]
Fixed. Please check https://stackblitz.com/edit/nextjs-react-windrose-chart?file=app%2Fpage.tsx
