### ISSUE TITLE
The production build in the npm package does not work

### ISSUE THREAD

**Issue by mmomtchev** [eunchurn/react-windrose-chart#143]
Maybe it is a compilation problem, but it does not export `Chart` - it exports `WindRose` and it does not work

**Comment by eunchurn** [comment]
What's you install command? e.g. `yarn add @eunchurn/react-windrose-chart`?

**Comment by mmomtchev** [comment]
Yes indeed, I was using `react-windrose-chart` instead of `eunchurn/react-windrose-chart`- you should probably deprecate the old one.

But with `eunchurn/react-windrose-chart` webpack fails to compile because
* it is missing `./src` which the sourcemaps reference
* there is a missing dependency for `d3`
* you should probably remove React as a runtime dependency (it was probably not on a purpose?), it should be only a `peerDependency` and `devDepedency` - because otherwise it leads to `react-windrose-chart` installing its own copy of React

**Comment by eunchurn** [comment]
I see i'll fix these issues asap. thank you.

**Comment by Radoslav22** [comment]
Hi, can you help me with this error. It seems like it is caused by the library itself. 
![image](https://github.com/eunchurn/react-windrose-chart/assets/71893647/33d8370e-b02e-41df-a09f-26b20f677637)

**Comment by Radoslav22** [comment]
![image](https://github.com/eunchurn/react-windrose-chart/assets/71893647/d0b77d63-315c-4809-89e4-f82a890a3193)
