### ISSUE TITLE
calculateWindRose does not return {data, columns} as it is described in readme

### ISSUE THREAD

**Issue by github0013** [eunchurn/react-windrose-chart#64]
https://github.com/eunchurn/react-windrose-chart#data-utils

> const windRoseData = calculateWindRose(data);
// Return {data, columns}

But actually it only returns apparently only the `data` part.

https://codesandbox.io/s/react-windrose-chart-calculatewindrose-7rgbu?file=/src/App.tsx

![react-windrose-chart_-_calculateWindRose_-_CodeSandbox](https://user-images.githubusercontent.com/809378/145902697-7cf588f0-cb8d-4209-a799-8145d7a9a983.png)

**Comment by joseangelconejominguez** [comment]
Hi, 

did you @github0013 face the same issue than me during the package installation? 
https://github.com/eunchurn/react-windrose-chart/issues/66

Cheers,
Jose

**Comment by github0013** [comment]
@joseangelconejominguez 
I am not sure it's been a long time since I tried this library.  You should always do barebones simple on codesandbox to see what is causing your issue.

**Comment by eunchurn** [comment]
I will check this issue, sorry for late..

**Comment by eunchurn** [comment]
resolves https://github.com/eunchurn/react-windrose-chart/commit/4c2c010c5720f7e866869925202e05262bb99aa5
