### ISSUE TITLE
WindRose's height is fixed at 600px no matter what value it gets as the height prop.

### ISSUE THREAD

**Issue by github0013** [eunchurn/react-windrose-chart#65]
https://github.com/eunchurn/react-windrose-chart/blob/5ea904c5003f66b34eb6f691f202171baa9d57fd/src/WindRose/WindRoseChart.component.js#L204

```jsx
      <WindRose
        width={1000}
        height={1000}
        data={...}
        columns={...}
      />
```

<img width="1168" alt="" src="https://user-images.githubusercontent.com/809378/145919774-9c8a87ce-a3b2-4b0d-acf9-db84d837059f.png">

I am thinking maybe you don't need to give it the height prop.   The height can always same as the width?

**Comment by eunchurn** [comment]
right. but i fixed it. i'll upgrade this chart soon. thank you for report.

![Screen Shot 2022-04-30 at 9 36 24](https://user-images.githubusercontent.com/7800413/166083582-2c4abdd0-6290-417b-a9bf-5799674ce4b6.png)
