### ISSUE TITLE
TypeError: undefined is not a function, js engine: hermes when importing 'react-windrose-chart'

### ISSUE THREAD

**Issue by joseangelconejominguez** [eunchurn/react-windrose-chart#66]
Hi, 

I am facing an issue when trying to import the package 'react-windrose-chart'. 

I used the following command for the installation:
**yarn add react-windrose-chart**

I also added styled-components to my project:
**yarn add styled-components**

However, when trying to import the package, I see the following message:

![image](https://user-images.githubusercontent.com/77481084/150822712-dbc91894-6a48-4257-8a5e-8da945bc5c98.png)

![image](https://user-images.githubusercontent.com/77481084/150824421-ac2b9629-35e5-470d-8a1c-e7f0fa8cc79d.png)

I would say that the error is in the styled-components package but I have no clue how I could fix this. 

Cheers, 
Jose

**Comment by eunchurn** [comment]
This package is for React.js.  I don't have enough time to make RN package for now. If you have simple guide to share this code between React.js DOM and RN, please notice me. I'm not familiar with RN.
