### ISSUE TITLE
Help: Need Preact instead of react :-)

### ISSUE THREAD

**Issue by OstertagM** [eunchurn/react-windrose-chart#67]
I am newbie but I know I can't use react. Could you help me to create your code using Preact instead?

**Comment by eunchurn** [comment]
works in `preact` too, but this package has `react` dependencies as shown below. are you using `preact` for the purpose like small packages?

```json
{
    "node_modules/react-windrose-chart": {
      "version": "0.2.2",
      "resolved": "https://registry.npmjs.org/react-windrose-chart/-/react-windrose-chart-0.2.2.tgz",
      "integrity": "sha512-Y/IbXuQjab+zfIo1OHzjhu1CbbLMgXD9tUhAMfZ0gAPDBSqsQr+6dfCSMvqS1Jmcngy4m8J6iYRcoi5BZZREvg==",
      "dependencies": {
        "d3": "^7.4.4",
        "react": "^18.1.0",
        "react-dom": "^18.1.0",
        "react-is": "^18.1.0",
        "styled-components": "^5.3.5"
      }
    }
}
```

I tested. creating plain preact project 
`npx preact-cli create preactjs-templates/default rw-preact-test`

and install package `npm install react-windrose-chart`

adding component in `src/routes/home/index.js` as below

```ts
import { h } from "preact";
import style from "./style.css";
import { Chart } from "react-windrose-chart";

const Home = () => (
  <div class={style.home}>
    <h1>Home</h1>
    <p>This is the Home component.</p>
    <Chart responsive />
  </div>
);

export default Home;
```
![Screen Shot 2022-05-01 at 4 55 04](https://user-images.githubusercontent.com/7800413/166120986-b847d766-aeae-41ec-900b-5b8fcb521c70.png)

I think this is not an issue.

**Comment by OstertagM** [comment]
> are you using preact for the purpose like small >packages?
No I want to build a custom card for home assistant (lovelace) and in this card type I can't use react.
​https://developers.home-assistant.io/docs/frontend/custom-ui/custom-card/#api
Thanks for this description I follow this way.

**Comment by eunchurn** [comment]
> The Home Assistant frontend is built using web components.

`web components` is difference with React. check <https://developer.mozilla.org/en-US/docs/Web/Web_Components>

<https://reactjs.org/docs/web-components.html>
> React and [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) are built to solve different problems. Web Components provide strong encapsulation for reusable components, while React provides a declarative library that keeps the DOM in sync with your data. The two goals are complementary. As a developer, you are free to use React in your Web Components, or to use Web Components in React, or both.

I'll try to make this as web components when I have some time.
